### ISSUE TITLE
FsRestfulApi.download接口下载结果集抛异常

### ISSUE THREAD

**Issue by liangqilang** [WeBankFinTech/Linkis#188]
**Describe the bug**
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_111]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_111]
        at org.springframework.cloud.gateway.filter.NettyRoutingFilter.lambda$filter$3(NettyRoutingFilter.java:117) ~[spring-cloud-gateway-core-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]

**To Reproduce**
1.  FsRestfulApi.download 接口下载_0.dolphin 结果集文件报错

**Comment by peacewong** [comment]
Thank you for fixing this issue，[PR 27](https://github.com/WeBankFinTech/Linkis/pull/225)
