### ISSUE TITLE
[Bug]spark enginemanager open debug mode

### ISSUE THREAD

**Issue by xccoder** [WeBankFinTech/Linkis#214]
**Describe the bug**
start spark-enginemanager debug mode,but start log show error

```

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=500m; support was removed in 8.0
Listening for transport dt_socket at address: 11732
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.webank.wedatasphere.linkis.server.conf.ServerConfiguration$.<init>(ServerConfiguration.scala:95)
        at com.webank.wedatasphere.linkis.server.conf.ServerConfiguration$.<clinit>(ServerConfiguration.scala)
        at com.webank.wedatasphere.linkis.server.conf.ServerConfiguration.BDP_SERVER_SPRING_APPLICATION_LISTENERS(ServerConfiguration.scala)
        at com.webank.wedatasphere.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:99)
Caused by: java.lang.IllegalArgumentException: For input string: "true    # æ<89><93>å¼<80>æµ<8b>è¯<95>æ¨¡å¼<8f>"
        at scala.collection.immutable.StringLike$class.parseBoolean(StringLike.scala:290)
        at scala.collection.immutable.StringLike$class.toBoolean(StringLike.scala:260)
        at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:29)
        at com.webank.wedatasphere.linkis.common.conf.BDPConfiguration$$anonfun$11.apply(BDPConfiguration.scala:97)
        at com.webank.wedatasphere.linkis.common.conf.BDPConfiguration$$anonfun$11.apply(BDPConfiguration.scala:97)
        at scala.Option.map(Option.scala:146)
        at com.webank.wedatasphere.linkis.common.conf.BDPConfiguration$.formatValue(BDPConfiguration.scala:97)
        at com.webank.wedatasphere.linkis.common.conf.BDPConfiguration$.getOption(BDPConfiguration.scala:83)
        at com.webank.wedatasphere.linkis.common.conf.CommonVars.<init>(CommonVars.scala:25)
        at com.webank.wedatasphere.linkis.common.conf.CommonVars$.apply(CommonVars.scala:37)
        at com.webank.wedatasphere.linkis.common.conf.Configuration$.<init>(Configuration.scala:35)
        at com.webank.wedatasphere.linkis.common.conf.Configuration$.<clinit>(Configuration.scala)
        ... 4 more
~                                                                                      
```
spark enginemange config :
![em](https://user-images.githubusercontent.com/16348865/70994694-bd259300-2109-11ea-9ea7-926b1214b8ed.png)

**Comment by xccoder** [comment]
Chinese annotation  cause errors

**Comment by wushengyeyouya** [comment]
Only happened on debug mode?

**Comment by xccoder** [comment]
yes，before linkis run normal,when  add " -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=10092" to sparkenginemanage start shell ,trigger error

**Comment by wushengyeyouya** [comment]
Seems like a bug, let us have a look, thanks very much.

**Comment by peacewong** [comment]
Hello, the issue has been fixed
