### ISSUE TITLE
获取yarn队列信息异常

### ISSUE THREAD

**Issue by ZhiYinZhang** [WeBankFinTech/Linkis#222]
查看了RESOURCEMANAGER的日志：
**Caused by: java.lang.ClassCastException: org.json4s.JsonAST$JNothing$ cannot be cast to org.json4s.JsonAST$JInt**
        at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$com$webank$wedatasphere$linkis$resourcemanager$utils$YarnUtil$$getYarnResource$1$1.apply(YarnUtil.scala:110) ~[linkis-resourcemanager-server-0.9.1.jar:?]
        at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$com$webank$wedatasphere$linkis$resourcemanager$utils$YarnUtil$$getYarnResource$1$1.apply(YarnUtil.scala:110) ~[linkis-resourcemanager-server-0.9.1.jar:?]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.8.jar:?]
        at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$.com$webank$wedatasphere$linkis$resourcemanager$utils$YarnUtil$$getYarnResource$1(YarnUtil.scala:110) ~[linkis-resourcemanager-server-0.9.1.jar:?]
        at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$4.apply(YarnUtil.scala:172) ~[linkis-resourcemanager-server-0.9.1.jar:?]
        at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$4.apply(YarnUtil.scala:162) ~[linkis-resourcemanager-server-0.9.1.jar:?]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.8.jar:?]
        at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.8.jar:?]
        at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.8.jar:?]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.8.jar:?]

**Comment by peacewong** [comment]
Hello, the issue has been fixed
