### ISSUE TITLE
【linkis-metadata】 start failed

### ISSUE THREAD

**Issue by caoenergy** [WeBankFinTech/Linkis#265]
**Describe the bug**
linkis-metadata start failed, java.lang.VerifyError: Cannot inherit from final class

**To Reproduce**
1.  setup all conf 
2. ./bin/start-all.sh > start.log 2>start_error.log

**Detail messages**
```
Start to Check if your microservice:linkis-metadata is normal via telnet
ERROR your linkis-metadata microservice is not start successful !!! ERROR logs as follows :
PLEAESE CHECK  DETAIL LOG,LOCATION:/opt/linkis-0.9.2/linkis-metadata/logs/linkis.out
<---------------------------------------------------->
Is local 0
2020-01-15 10:19:51,626 INFO  (background-preinit) INFO Version - HV000001: Hibernate Validator 5.1.2.Final
2020-01-15 10:19:52,922 INFO  (main) INFO AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@495083a0: startup date [Wed Jan 15 10:19:52 CST 2020]; root of context hierarchy
2020-01-15 10:19:53,903 INFO  (main) INFO AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2020-01-15 10:19:54,075 INFO  (main) INFO PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$ca25fa00] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.3.RELEASE)

2020-01-15 10:19:55,297 ERROR (main) ERROR SpringApplication - Application run failed
java.lang.VerifyError: Cannot inherit from final class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.fasterxml.jackson.datatype.jdk8.Jdk8Module.setupModule(Jdk8Module.java:30)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:524)
        at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.registerWellKnownModulesIfAvailable(Jackson2ObjectMapperBuilder.java:734)
        at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.configure(Jackson2ObjectMapperBuilder.java:624)
        at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:608)
        at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.<init>(MappingJackson2HttpMessageConverter.java:59)
        at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:74)
        at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:179)
        at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:218)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getSecureRestTemplate(ConfigServicePropertySourceLocator.java:256)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:83)
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
        at com.webank.wedatasphere.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:105)
```
**Eurkea service**

BML-SERVER | n/a (1) | (1) | UP (1) -                         bml-server:9113
-- | -- | -- | --
CLOUD-PUBLICSERVICE | n/a (1) | (1) | UP (1) -                         cloud-publicservice:9102
DATAWORKCLOUD | n/a (1) | (1) | UP (1) -                         DataWorkCloud:20303
DATAWORKCLOUD-GATEWAY | n/a (1) | (1) | UP (1) -                         DataWorkCloud-Gateway:9001
HIVEENTRANCE | n/a (1) | (1) | UP (1) -                         hiveEntrance:9108
JDBCENTRANCE | n/a (1) | (1) | UP (1) -                         jdbcEntrance:9111
PYTHONENGINEMANAGER | n/a (1) | (1) | UP (1) -                         pythonEngineManager:9109
PYTHONENTRANCE | n/a (1) | (1) | UP (1) -                         pythonentrance:9110
RESOURCEMANAGER | n/a (1) | (1) | UP (1) -                         ResourceManager:9104
SPARKENGINEMANAGER | n/a (1) | (1) | UP (1) -                         sparkEngineManager:9105
SPARKENTRANCE | n/a (1) | (1) | UP (1) -                         sparkEntrance:9106

**Desktop (please complete the following information):**
 - OS: Red Hat 7.3
 - linkis-0.9.2 (baiduwangpan: wedatasphere-linkis-0.9.2-dist-CDH5.7.6-spark2.0-2.2.tar.gz )
- jdk1.8.0_181

**Comment by frank-zx** [comment]
如果你部署的是wedatasphere-linkis-0.9.2-dist-CDH5.7.6-spark2.0-2.2.tar.gz，可以把lib里一些旧版本同名jar包删掉，应该是jar版本冲突，就可以了。
我是自己编译的，现在也遇到这个问题，删jar包已经解决不了了....

**Comment by peacewong** [comment]
This problem has been fixed, you can refer to pr:[272](https://github.com/WeBankFinTech/Linkis/pull/272)
