### ISSUE TITLE
Not registered in the resource manager

### ISSUE THREAD

**Issue by jiaorenyu** [WeBankFinTech/Linkis#266]
How can I fix this problem?

```

Module instance(模块实例): ServiceInstance(pythonEngineManager, nb-withwind-runtask02:9109) Not registered in the resource manager(并没有在资源管理器进行注册)
2020-01-15 11:55:45.055 ERROR Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!
2020-01-15 11:55:45.055 ERROR DWCException{errCode=110005, desc='Module instance(模块实例): ServiceInstance(pythonEngineManager, nb-withwind-runtask02:9109) Not registered in the resource manager(并没有在资源管理器进行注册)', ip='nb-withwind-runtask02', port=9104, serviceKind='ResourceManager'}
	at com.webank.wedatasphere.linkis.common.exception.ExceptionManager.generateException(ExceptionManager.java:52)
	at com.webank.wedatasphere.linkis.rpc.transform.RPCConsumer$$anon$1.toObject(RPCConsumer.scala:67)
	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$ask$1.apply(BaseRPCSender.scala:87)
	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorExchange.invoke(RPCInterceptorExchange.scala:32)
	at com.webank.wedatasphere.linkis.rpc.interceptor.common.CommonRPCInterceptor.intercept(CommonRPCInterceptor.scala:29)
	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor$$anonfun$intercept$1.apply(RetryableRPCInterceptor.scala:53)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.common.utils.RetryHandler$class.retry(RetryHandler.scala:56)
	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor$RPCRetryHandler.retry(RetryableRPCInterceptor.scala:58)
	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor.intercept(RetryableRPCInterceptor.scala:53)
	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
	at com.webank.wedatasphere.linkis.rpc.interceptor.common.CacheableRPCInterceptor.intercept(CacheableRPCInterceptor.scala:57)
	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
	at com.webank.wedatasphere.linkis.rpc.interceptor.common.BroadcastRPCInterceptor.intercept(BroadcastRPCInterceptor.scala:74)
	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.execute(BaseRPCSender.scala:79)
	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.ask(BaseRPCSender.scala:83)
	at com.webank.wedatasphere.linkis.entrance.execute.EngineRequester.request(EngineRequester.scala:51)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceExecutorManager.createExecutor(EntranceExecutorManager.scala:66)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceExecutorManager$$anonfun$askExecutor$1.apply(EntranceExecutorManager.scala:112)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceExecutorManager$$anonfun$askExecutor$1.apply(EntranceExecutorManager.scala:111)
	at scala.Option.orElse(Option.scala:289)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceExecutorManager.askExecutor(EntranceExecutorManager.scala:111)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceExecutorManager$$anonfun$4.apply(EntranceExecutorManager.scala:129)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceExecutorManager$$anonfun$4.apply(EntranceExecutorManager.scala:129)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceExecutorManager.askExecutor(EntranceExecutorManager.scala:129)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcZ$sp$2.apply(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcZ$sp$2.apply(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1.apply$mcZ$sp(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.aux$1(Utils.scala:191)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.waitUntil(Utils.scala:204)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.waitUntil(Utils.scala:207)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply$mcV$sp(FIFOUserConsumer.scala:112)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply(FIFOUserConsumer.scala:108)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply(FIFOUserConsumer.scala:108)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:133)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:107)
	at scala.Option.foreach(Option.scala:257)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.loop(FIFOUserConsumer.scala:107)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply$mcV$sp(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.run(FIFOUserConsumer.scala:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-15 11:55:45.055 INFO Task creation time(任务创建时间): 2020-01-15 11:55:42, Task scheduling time(任务调度时间): 2020-01-15 11:55:43, Task start time(任务开始时间): not started, Mission end time(任务结束时间): 2020-01-15 11:55:45
2020-01-15 11:55:45.055 INFO Your mission(您的任务) 1 The total time spent is(总耗时时间为): 2.5 秒
2020-01-15 11:55:45.055 INFO Sorry. Your job completed with a status Failed. You can view logs for the reason.
```

**Comment by jiaorenyu** [comment]
是因为engine没有启动，解决方案参见：https://github.com/WeBankFinTech/Linkis/wiki/%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BC%96%E8%AF%91%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93

第13条，如下：

> 13.因为Linkis启动enine使用的是expect语法，在脚本中需要命令提示符界面展示为如此[root@localhost ~]# 如果不是，需要修改，在.bashrc里面配置：export PS1='[\u@\h \W]\$ '
