### ISSUE TITLE
JavaSDK提交SQL至JDBC Engine，运行出错 

### ISSUE THREAD

**Issue by frank-zx** [WeBankFinTech/Linkis#275]
使用Java SDK调用JDBC Engine，调用代码如下：
```
Map<String,Object> params = new HashMap<>();
params.put("jdbc.url","jdbc:hive2://x.x.x.x:x/default");
params.put("jdbc.username","xxx");
params.put("jdbc.password","xxx");
JobExecuteResult jobExecuteResult = client.execute(JobExecuteAction.builder().setCreator("UJESClient-Test")
                .addExecuteCode("select 1")
                .setEngineTypeStr("jdbc")
                .setRunTypeStr("sql")
                .setParams(params)
                .setUser("xxx")
                .build()
        );
```

jdbc-entrance报错如下：

> 2020-01-21 09:26:47,652 INFO  (qtp718053924-1121) INFO EntranceRestfulApi - Begin to get an execID
2020-01-21 09:26:47,653 INFO  (qtp718053924-1121) INFO DefaultEntranceServer - received a request: {runType=sql, executionCode=select 1, executeApplicationName=jdbc, source={}, params={jdbc.password=xxx, jdbc.url=jdbc:hive2://x.x.x.x:x/default, jdbc.username=xxx}, requestApplicationName=UJESClient-Test, umUser=xxx}
2020-01-21 09:26:47,759 INFO  (UJESClient-Test_xxxConsumerThread) INFO JDBCEntranceJob - UJESClient-Test_xxx_1 change state Inited => Scheduled.
2020-01-21 09:26:47,761 INFO  (qtp718053924-1121) INFO DefaultEntranceServer - Job UJESClient-Test_xxx_1 submitted and taskID is 37
2020-01-21 09:26:47,763 INFO  (qtp718053924-1121) INFO EntranceRestfulApi - End to get an an execID: 150444UJESClient-Testjdbcx.x.x.x.x:9111UJESClient-Test_xxx_1, taskID: 37
2020-01-21 09:26:47,787 INFO  (UJESClient-Test_xxxConsumerThread) INFO JDBCEngineExecutorManagerImpl - BEGAIN TO GET configuration：null
2020-01-21 09:26:47,787 INFO  (UJESClient-Test_xxxConsumerThread) INFO JDBCEntranceJob - job UJESClient-Test_xxx_1 is onFailure on state Scheduled with errorMsg: Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!.
2020-01-21 09:26:47,789 INFO  (jdbcEntrance-EventListenerBus-Thread-0) INFO EntranceWebSocketService -  retMessage: execID is 150444UJESClient-Testjdbcx.x.x.x.x:9111UJESClient-Test_xxx_1, status is Scheduled, websocketTag is null
2020-01-21 09:26:47,810 WARN  (UJESClient-Test_xxxConsumerThread) WARN JDBCEntranceJob - This executor of job(UJESClient-Test_xxx_1) in starting status,When kill job need to interrupter consumer Future
2020-01-21 09:26:47,810 INFO  (UJESClient-Test_xxxConsumerThread) INFO BDPFutureTask - Start to interrupt BDPFutureTask
2020-01-21 09:26:47,810 INFO  (UJESClient-Test_xxxConsumerThread) INFO BDPFutureTask - Finished to interrupt BDPFutureTask of UJESClient-Test_xxxConsumerThread
2020-01-21 09:26:47,810 INFO  (UJESClient-Test_xxxConsumerThread) INFO JDBCEntranceJob - UJESClient-Test_xxx_1 change state Scheduled => Failed.
2020-01-21 09:26:47,848 INFO  (UJESClient-Test_xxxConsumerThread) INFO EntranceExecutionJob - job:UJESClient-Test_xxx_1 is closing
2020-01-21 09:26:47,848 INFO  (jdbcEntrance-EventListenerBus-Thread-0) INFO EntranceWebSocketService -  retMessage: execID is 150444UJESClient-Testjdbcx.x.x.x.x:9111UJESClient-Test_xxx_1, status is Failed, websocketTag is null
2020-01-21 09:26:47,849 INFO  (UJESClient-Test_xxxConsumerThread) INFO JDBCEntranceJob - UJESClient-Test_xxx_1 execute failed. Reason: Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!.
java.lang.NullPointerException
	at com.webank.wedatasphere.linkis.entrance.executer.JDBCEngineExecutorManagerImpl.findUsefulExecutor(JDBCEngineExecutorManagerImpl.scala:99)
	at com.webank.wedatasphere.linkis.entrance.executer.JDBCEngineExecutorManagerImpl.askExecutor(JDBCEngineExecutorManagerImpl.scala:90)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcZ$sp$2.apply(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcZ$sp$2.apply(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1.apply$mcZ$sp(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.aux$1(Utils.scala:191)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.waitUntil(Utils.scala:204)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.waitUntil(Utils.scala:207)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply$mcV$sp(FIFOUserConsumer.scala:112)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply(FIFOUserConsumer.scala:108)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply(FIFOUserConsumer.scala:108)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:133)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:107)
	at scala.Option.foreach(Option.scala:257)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.loop(FIFOUserConsumer.scala:107)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply$mcV$sp(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.run(FIFOUserConsumer.scala:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-21 09:26:47,849 WARN  (UJESClient-Test_xxxConsumerThread) WARN FIFOUserConsumer - Ask executor for Job UJESClient-Test_xxx_1 failed!
java.lang.NullPointerException
	at com.webank.wedatasphere.linkis.entrance.executer.JDBCEngineExecutorManagerImpl.findUsefulExecutor(JDBCEngineExecutorManagerImpl.scala:99)
	at com.webank.wedatasphere.linkis.entrance.executer.JDBCEngineExecutorManagerImpl.askExecutor(JDBCEngineExecutorManagerImpl.scala:90)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcZ$sp$2.apply(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcZ$sp$2.apply(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3$$anonfun$apply$mcV$sp$1.apply$mcZ$sp(FIFOUserConsumer.scala:113)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.aux$1(Utils.scala:191)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.waitUntil(Utils.scala:204)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.waitUntil(Utils.scala:207)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply$mcV$sp(FIFOUserConsumer.scala:112)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply(FIFOUserConsumer.scala:108)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$3.apply(FIFOUserConsumer.scala:108)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:133)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:107)
	at scala.Option.foreach(Option.scala:257)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.loop(FIFOUserConsumer.scala:107)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply$mcV$sp(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102)
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.run(FIFOUserConsumer.scala:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by chaogefeng** [comment]
@frank-zx 
Using setRuntimeParams method will work.
```
Map<String,Object> params = new HashMap<>();
params.put("jdbc.url","jdbc:hive2://x.x.x.x:x/default");
params.put("jdbc.username","xxx");
params.put("jdbc.password","xxx");
JobExecuteResult jobExecuteResult = client.execute(JobExecuteAction.builder().setCreator("UJESClient-Test")
                .addExecuteCode("select 1")
                .setEngineTypeStr("jdbc")
                .setRunTypeStr("sql")
                .setRuntimeParams(params)
                .setUser("xxx")
                .build()
        );
```
