### ISSUE TITLE
在启动spark引擎执行sql时报错

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [WeBankFinTech/Linkis#324]
通过spark引擎执行sql时，日志里面报错，进行sql计算，调用spark引擎时报错Caused by: java.lang.ClassCastException: org.apache.hadoop.fs.FsUrlConnection cannot be cast to java.net.HttpURLConnection
详细日志：
2020-03-11 14:47:35-746 WARN  [BDP-Default-Scheduler-Thread-10] com.webank.wedatasphere.linkis.engine.EngineReceiver com.webank.wedatasphere.linkis.common.utils.Utils$$anonfun$tryAndWarn$1.apply(Utils.scala:84) apply - java.lang.RuntimeException: com.netflix.client.ClientException
36795: 	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:71) ~[spring-cloud-openfeign-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
36795: 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97) ~[feign-core-9.5.1.jar:?]
36795: 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.1.jar:?]
36795: 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.5.1.jar:?]
36795: 	at com.sun.proxy.$Proxy141.receive(Unknown Source) ~[?:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$send$1.apply(BaseRPCSender.scala:107) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$send$1.apply(BaseRPCSender.scala:107) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$sendIt$1.apply(BaseRPCSender.scala:101) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorExchange.invoke(RPCInterceptorExchange.scala:32) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.CommonRPCInterceptor.intercept(CommonRPCInterceptor.scala:29) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor$$anonfun$intercept$1.apply(RetryableRPCInterceptor.scala:53) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) ~[linkis-common-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.common.utils.RetryHandler$class.retry(RetryHandler.scala:56) ~[linkis-common-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor$RPCRetryHandler.retry(RetryableRPCInterceptor.scala:58) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor.intercept(RetryableRPCInterceptor.scala:53) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.CacheableRPCInterceptor.intercept(CacheableRPCInterceptor.scala:57) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.BroadcastRPCInterceptor.intercept(BroadcastRPCInterceptor.scala:74) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.execute(BaseRPCSender.scala:79) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.sendIt(BaseRPCSender.scala:98) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.send(BaseRPCSender.scala:107) ~[linkis-cloudRPC-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$com$webank$wedatasphere$linkis$engine$EngineReceiver$$send$1$$anonfun$apply$3.apply$mcV$sp(EngineReceiver.scala:258) ~[linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$com$webank$wedatasphere$linkis$engine$EngineReceiver$$send$1$$anonfun$apply$3.apply(EngineReceiver.scala:258) ~[linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$com$webank$wedatasphere$linkis$engine$EngineReceiver$$send$1$$anonfun$apply$3.apply(EngineReceiver.scala:258) ~[linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:74) [linkis-common-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$com$webank$wedatasphere$linkis$engine$EngineReceiver$$send$1.apply(EngineReceiver.scala:258) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$com$webank$wedatasphere$linkis$engine$EngineReceiver$$send$1.apply(EngineReceiver.scala:258) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.8.jar:?]
36795: 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.8.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver.com$webank$wedatasphere$linkis$engine$EngineReceiver$$send(EngineReceiver.scala:258) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$onLogUpdate$1$$anonfun$apply$10$$anonfun$apply$4.apply$mcV$sp(EngineReceiver.scala:306) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$onLogUpdate$1$$anonfun$apply$10$$anonfun$apply$4.apply(EngineReceiver.scala:306) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$onLogUpdate$1$$anonfun$apply$10$$anonfun$apply$4.apply(EngineReceiver.scala:306) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:74) [linkis-common-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$onLogUpdate$1$$anonfun$apply$10.apply(EngineReceiver.scala:306) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$onLogUpdate$1$$anonfun$apply$10.apply(EngineReceiver.scala:305) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.8.jar:?]
36795: 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.8.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$onLogUpdate$1.apply(EngineReceiver.scala:305) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver$$anonfun$onLogUpdate$1.apply(EngineReceiver.scala:305) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.8.jar:?]
36795: 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.8.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver.onLogUpdate(EngineReceiver.scala:305) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at com.webank.wedatasphere.linkis.engine.log.SendAppender$SendThread.run(SendAppender.java:70) [linkis-ujes-engine-0.9.3.jar:?]
36795: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
36795: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_65]
36795: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_65]
36795: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_65]
36795: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
36795: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
36795: 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
36795: Caused by: com.netflix.client.ClientException
36795: 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:118) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]
36795: 	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63) ~[spring-cloud-openfeign-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
36795: 	... 55 more
36795: Caused by: java.lang.ClassCastException: org.apache.hadoop.fs.FsUrlConnection cannot be cast to java.net.HttpURLConnection
36795: 	at feign.Client$Default.convertAndSend(Client.java:80) ~[feign-core-9.5.1.jar:?]
36795: 	at feign.Client$Default.execute(Client.java:73) ~[feign-core-9.5.1.jar:?]
36795: 	at org.springframework.cloud.openfeign.ribbon.FeignLoadBalancer.execute(FeignLoadBalancer.java:89) ~[spring-cloud-openfeign-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
36795: 	at org.springframework.cloud.openfeign.ribbon.FeignLoadBalancer.execute(FeignLoadBalancer.java:55) ~[spring-cloud-openfeign-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
36795: 	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]
36795: 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]
36795: 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]
36795: 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.Observable.subscribe(Observable.java:10247) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.Observable.subscribe(Observable.java:10214) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at rx.observables.BlockingObservable.single(BlockingObservable.java:341) ~[rxjava-1.2.0.jar:1.2.0]
36795: 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]
36795: 	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63) ~[spring-cloud-openfeign-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
36795: 	... 55 more

**Comment by WholeWorld-Timothy** [comment]
重新按照当前hadoop和spark版本编译后，没在出现错误
