### ISSUE TITLE
[ERROR]Max frame length of 65536 has been exceeded.

### ISSUE THREAD

**Issue by Shmilyqjj** [WeBankFinTech/Linkis#476]
**Linkis - Max frame length of 65536 has been exceeded**
dss代码框单次提交运行的代码长度大于等于65536字节，websocket会无法发送（netty限制数据帧大小65536），导致任务一直排队中。
OS:Centos7
Linkis version:0.9.3

**To Reproduce**
1. 进入dss
2. 进入scripts
3. 输入大于等于65536字节的注释或代码，tailf linkis gateway日志
4. See error：Max frame length of 65536 has been exceeded

```
2020-07-08 19:01:15.952 ERROR [reactor-http-nio-7] reactor.ipc.netty.channel.ContextHandler 300 error - Error cannot be forwarded to user-facing Mono io.netty.handler.codec.CorruptedFrameException: Max frame length of 65536 has been exceeded.
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412) ~[netty-codec-http-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:277) ~[netty-codec-http-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar:4.1.25.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

2020-07-08 19:01:15.953 WARN  [reactor-http-nio-7] io.netty.channel.AbstractChannelHandlerContext 146 warn - An exception 'reactor.core.Exceptions$ErrorCallbackNotImplemented: io.netty.handler.codec.CorruptedFrameException: Max frame length of 65536 has been exceeded.' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception: io.netty.handler.codec.CorruptedFrameException: Max frame length of 65536 has been exceeded.
```

**Expected behavior**
期待结果是可以通过配置参数来自定义max frame size。

**Comment by peacewong** [comment]
Hello, this problem has been solved in version 1.0-RC1, you can refer to file[WebSocketServiceConfiguration.java](https://github.com/WeBankFinTech/Linkis/blob/master/linkis-spring-cloud-services/linkis-service-gateway/linkis-spring-cloud-gateway/src/main/java/com/webank/wedatasphere/linkis/gateway/springcloud/websocket/WebSocketServiceConfiguration.java):
```
 public static final CommonVars<Integer> MAX_FRAME_LENGTH = CommonVars$.MODULE$.apply("wds.linkis.gateway.conf.max.frame.length", 655350);

    @Bean(name = "customWebSocketService")
    @Primary
    public WebSocketService webSocketService() {
        ReactorNettyRequestUpgradeStrategy strategy = new ReactorNettyRequestUpgradeStrategy();
        strategy.setMaxFramePayloadLength(MAX_FRAME_LENGTH.getValue());
        return new HandshakeWebSocketService(strategy);
    }
```
By adjusting MaxFramePayloadLength of WebSocketService. If you are using version 0.X, you can create the same customWebSocketService Bean in the springcloudgateway module.
