### ISSUE TITLE
You must register IOMethodInterceptorCreator before you can use proxy mode

### ISSUE THREAD

**Issue by geosmart** [WeBankFinTech/Linkis#695]
linkis deploy with docker ,deployUser=root

run testcase of `com.webank.wedatasphere.linkis.ujes.client.LinkisClientTest` 
setAuthTokenKey(user) is not root, 
get an exception `You must register IOMethodInterceptorCreator before you can use proxy mode`
how can I fix this exception!

error log:
```java
2021-03-29 13:01:59.825 [INFO ] [linkisClient-Test_jrsyb_ops_hiveConsumerThread] c.w.w.l.e.j.EntranceExecutionJob (42) [info] - job linkisClient-Test_jrsyb_ops_hive_0 is onFailure on state Scheduled with errorMsg: 请求引擎失败，可能是由于后台进程错误!请联系管理员.
2021-03-29 13:01:59.828 [WARN ] [linkisClient-Test_jrsyb_ops_hiveConsumerThread] c.w.w.l.e.l.CacheLogManager (55) [apply] - write log for job linkisClient-Test_jrsyb_ops_hive_0 failed com.webank.wedatasphere.linkis.storage.exception.StorageErrorException: errCode: 52004 ,desc: You must register IOMethodInterceptorCreator before you can use proxy mode.(必须先注册IOMethodInterceptorCreator，才能使用代理模式) ,ip: 10.204.128.7 ,port: 9104 ,serviceKind: linkis-cg-entrance
	at com.webank.wedatasphere.linkis.storage.io.IOMethodInterceptorCreator$.getIOMethodInterceptor(IOMethodInterceptorCreator.scala:41) ~[linkis-storage-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.storage.factory.impl.BuildLocalFileSystem.getProxyFs(BuildLocalFileSystem.java:51) ~[linkis-storage-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.storage.factory.impl.BuildLocalFileSystem.getFs(BuildLocalFileSystem.java:37) ~[linkis-storage-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.storage.FSFactory$.getFs(FSFactory.scala:38) ~[linkis-storage-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.storage.FSFactory$.getFsByProxyUser(FSFactory.scala:75) ~[linkis-storage-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.log.AbstractLogWriter.<init>(LogWriter.scala:79) ~[linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.log.CacheLogWriter.<init>(CacheLogWriter.scala:31) ~[linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.log.CacheLogManager.createLogWriter(CacheLogManager.scala:62) ~[linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.log.LogManager$$anonfun$onLogUpdate$1.apply$mcV$sp(LogManager.scala:45) ~[linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.log.LogManager$$anonfun$onLogUpdate$1.apply(LogManager.scala:42) ~[linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.log.LogManager$$anonfun$onLogUpdate$1.apply(LogManager.scala:42) ~[linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.log.LogManager.onLogUpdate(LogManager.scala:54) [linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.Job$$anonfun$onFailure$1$$anonfun$apply$mcV$sp$1.apply(Job.scala:94) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.Job$$anonfun$onFailure$1$$anonfun$apply$mcV$sp$1.apply(Job.scala:94) [linkis-scheduler-1.0.0-RC1.jar:?]
	at scala.Option.foreach(Option.scala:257) [scala-library-2.11.12.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.Job$$anonfun$onFailure$1.apply$mcV$sp(Job.scala:94) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.Job$$anonfun$onFailure$1.apply(Job.scala:93) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.Job$$anonfun$onFailure$1.apply(Job.scala:93) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:74) [linkis-common-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.Job.onFailure(Job.scala:93) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceJob.onFailure(EntranceJob.scala:154) [linkis-entrance-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$10.apply(FIFOUserConsumer.scala:150) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3$$anonfun$apply$10.apply(FIFOUserConsumer.scala:144) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:54) [linkis-common-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:144) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$loop$3.apply(FIFOUserConsumer.scala:117) [linkis-scheduler-1.0.0-RC1.jar:?]
	at scala.Option.foreach(Option.scala:257) [scala-library-2.11.12.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.loop(FIFOUserConsumer.scala:117) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply$mcV$sp(FIFOUserConsumer.scala:82) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:82) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:82) [linkis-scheduler-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102) [linkis-common-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.run(FIFOUserConsumer.scala:82) [linkis-scheduler-1.0.0-RC1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_281]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
```

**Comment by peacewong** [comment]
Hello, you can modify the log directory of the linkis-entrance service to the HDFS path, `wds.linkis.entrance.config.log.path=hdfs://`.  The RC1 version does not support the proxy mode of the local path

**Comment by geosmart** [comment]
thanks @peacewong ,issue resolved
