### ISSUE TITLE
com.webank.wedatasphere.linkis.resourcemanager.exception.RMWarnException: errCode: 111006 ,desc: queue ide1 is not exists in YARN

### ISSUE THREAD

**Issue by xiejueheng** [WeBankFinTech/Linkis#704]
**Describe the bug**

[ERROR] [qtp2094809200-50                        ] c.w.w.l.r.RPCReceiveRestful (72) [apply] - error code(错误码): 111006, error message(错误信息): Get the Yarn queue information exception.(获取Yarn队列信息异常). 

com.webank.wedatasphere.linkis.resourcemanager.exception.RMErrorException: errCode: 111006 ,desc: Get the Yarn queue information exception.(获取Yarn队列信息异常) ,ip: jungle-1.thinkinpower.com ,port: 9104 ,serviceKind: ResourceManager

Caused by: com.webank.wedatasphere.linkis.resourcemanager.exception.RMWarnException: errCode: 111006 ,desc: queue ide1 is not exists in YARN. ,ip: jungle-1.thinkinpower.com ,port: 9104 ,serviceKind: ResourceManager
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$5.apply(YarnUtil.scala:202) ~[linkis-resourcemanager-server-0.9.3.jar:?]
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$5.apply(YarnUtil.scala:186) ~[linkis-resourcemanager-server-0.9.3.jar:?]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.8.jar:?]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.8.jar:?]
	at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.8.jar:?]

**To Reproduce**
1. 打开Scriptis
2. 新建脚本
3. 输入select * from sample_table;
4. 点击“运行”
5. 出现错误：60035资源不足，启动引擎失败
6. 点击“查看”

2021-04-07 17:41:27.041 ERROR Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!
2021-04-07 17:41:27.041 ERROR DWCException{errCode=111006, desc='Get the Yarn queue information exception.(获取Yarn队列信息异常)', ip='jungle-1.thinkinpower.com', port=9104, serviceKind='ResourceManager'}

**Comment by peacewong** [comment]
Hello, you can set the existing and authorized Yarn queue in Settings - Universal Settings
