### ISSUE TITLE
run python script fail

### ISSUE THREAD

**Issue by audaq** [WeBankFinTech/Linkis#9]
python 
    print 123

ERROR
2019-07-25 22:08:37.398 INFO  [qtp1192854820-28] com.webank.wedatasphere.linkis.filesystem.service.FsService 79 getFileSystem - com.webank.wedatasphere.linkis.filesystem.exception.W
orkSpaceException: Requesting IO-Engine to initialize fileSystem failed!(请求IO-Engine初始化fileSystem失败！)
2019-07-25 22:08:37.398 INFO  [qtp1192854820-28] com.webank.wedatasphere.linkis.filesystem.service.FsService 87 getFileSystem - leeli gets the hdfs type filesystem using a total of 
1 milliseconds(leeli获取hdfs类型的filesystem一共使用了1毫秒)
2019-07-25 22:08:37.398 ERROR [qtp1192854820-28] com.webank.wedatasphere.linkis.server.restful.RestfulCatchAOP 83 apply - operation failed(操作失败)s com.webank.wedatasphere.linkis.
filesystem.exception.WorkSpaceException: The user has obtained the filesystem for more than 2s. Please contact the administrator.（用户获取filesystem的时间超过2s，请联系管理员）
        at com.webank.wedatasphere.linkis.filesystem.restful.api.FsRestfulApi.fsValidate(FsRestfulApi.java:101) ~[linkis-workspace-0.5.0.jar:?]
        at com.webank.wedatasphere.linkis.filesystem.restful.api.FsRestfulApi.getDirFileTrees(FsRestfulApi.java:258) ~[linkis-workspace-0.5.0.jar:?]
        at com.webank.wedatasphere.linkis.filesystem.restful.api.FsRestfulApi$$FastClassBySpringCGLIB$$1392dc82.invoke(<generated>) ~[linkis-workspace-0.5.0.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at com.webank.wedatasphere.linkis.server.restful.RestfulCatchAOP$$anonfun$1.apply(RestfulCatchAOP.scala:48) ~[linkis-module-0.5.0.jar:?]
        at com.webank.wedatasphere.linkis.server.restful.RestfulCatchAOP$$anonfun$1.apply(RestfulCatchAOP.scala:48) ~[linkis-module-0.5.0.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.5.0.jar:?]
        at com.webank.wedatasphere.linkis.server.package$.catchMsg(package.scala:57) [linkis-module-0.5.0.jar:?]
        at com.webank.wedatasphere.linkis.server.package$.catchIt(package.scala:89) [linkis-module-0.5.0.jar:?]
        at com.webank.wedatasphere.linkis.server.restful.RestfulCatchAOP.dealResponseRestful(RestfulCatchAOP.scala:47) [linkis-module-0.5.0.jar:?]
        at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]

**Comment by yangzhiyue** [comment]
Thanks for your issue. As your log shows, I reckon that in your config.sh WPRKSPACE_PATH should end with "/" like below
```
WORKSPACE_PATH=file:///tmp/linkis/
HDFS_PATH=hdfs:///tmp/linkis/
```
