### ISSUE TITLE
NullPointerException occurred when running SQL, pyspark and Scala

### ISSUE THREAD

**Issue by coralzu** [WeBankFinTech/Linkis#927]
**Describe the bug**
creating nodes of SQL, pyspark and scala types in the workflow, null pointer exceptions are reported at runtime

**To Reproduce**
1. Enter the workflow and create an SQL type node
2. Edit the SQL node content and click the run button
3. Error log reported

**Expected behavior**
Run SQL correctly and get results.

**Screenshots**
**Web Log**
![image](https://user-images.githubusercontent.com/45164615/127275208-924cd4e4-fb96-4b27-962c-547db682c42d.png)

**linkis-ujes-spark-enginemanager Log**
```
2021-07-28 14:33:57.250 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration
2021-07-28 14:38:22.625 INFO  [qtp1283050069-23] com.webank.wedatasphere.linkis.enginemanager.impl.EngineManagerImpl 42 info - User root wants to request a new engine, messages: TimeoutRequestNewEngine(1200000,root,IDE,{_req_entrance_instance=sparkEntrance,172.17.0.90:9106})
2021-07-28 14:38:22.659 INFO  [qtp1283050069-23] com.webank.wedatasphere.linkis.enginemanager.hook.JarLoaderEngineHook 42 info - start loading UDFs
2021-07-28 14:38:22.703 INFO  [qtp1283050069-23] com.webank.wedatasphere.linkis.enginemanager.hook.JarLoaderEngineHook 42 info - added jars: 
2021-07-28 14:38:22.704 INFO  [qtp1283050069-23] com.webank.wedatasphere.linkis.enginemanager.hook.JarLoaderEngineHook 42 info - end loading UDFs
2021-07-28 14:38:22.826 INFO  [qtp1283050069-23] com.webank.wedatasphere.linkis.enginemanager.EngineManagerReceiver 42 info - User root, created a new engine SparkCommonProcessEngine(port: 37112, creator: IDE, user: root), creator=IDE
2021-07-28 14:38:22.828 INFO  [Engine-Manager-Thread-11] com.webank.wedatasphere.linkis.enginemanager.process.SparkSubmitProcessBuilder 42 info - Running spark-submit --master yarn --deploy-mode client --name linkis --conf spark.driver.extraJavaOptions="-Dwds.linkis.configuration=linkis-engine.properties -Duser.timezone=Asia/Shanghai " --conf spark.driver.cores=1 --driver-memory 1G --driver-class-path /soft/dataspherestudio/spark-2.3.4-bin-hadoop2.7/conf:/appcom/config/hadoop-config:/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/conf:/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/lib/* --driver-cores 1 --executor-memory 3G --executor-cores 2 --num-executors 1 --queue default --class com.webank.wedatasphere.linkis.engine.DataWorkCloudEngineApplication  /soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/lib/linkis-ujes-spark-engine-0.11.0.jar --dwc-conf _req_entrance_instance=sparkEntrance,172.17.0.90:9106 --dwc-conf wds.linkis.yarnqueue.memory.max=8G --dwc-conf wds.linkis.preheating.time=9:00 --dwc-conf wds.linkis.instance=1 --dwc-conf wds.linkis.tmpfile.clean.time=10:00 --dwc-conf ticketId=02381aac-13ea-40bc-962c-3bacc7b17b71 --dwc-conf dwc.application.instance=172.17.0.90:9105 --dwc-conf spark.driver.memory=1 --dwc-conf spark.executor.instances=1 --dwc-conf creator=IDE --dwc-conf spark.driver.cores=1 --dwc-conf wds.linkis.yarnqueue=default --dwc-conf wds.linkis.yarnqueue.cores.max=4 --dwc-conf spark.executor.memory=3 --dwc-conf spark.executor.cores=2 --dwc-conf wds.linkis.client.memory.max=4G --dwc-conf dwc.application.name=sparkEngineManager --dwc-conf user=root --spring-conf eureka.client.serviceUrl.defaultZone=http://127.0.0.1:20303/eureka/ --spring-conf logging.config=classpath:log4j2-engine.xml --spring-conf spring.profiles.active=engine --spring-conf server.port=37112 --spring-conf spring.application.name=sparkEngine
37112: spawn sudo su -
37112: 上一次登录：三 7月 28 14:21:13 CST 2021pts/3 上
37112: [root@gbd-01 ~]# su - root
37112: 上一次登录：三 7月 28 14:38:22 CST 2021pts/3 上
37112: [root@gbd-01 ~]# spark-submit --master yarn --deploy-mode client --name linkis --conf spark.driver.extraJavaOptions="-Dwds.linkis.configuration=linkis-engine.properties -Duser.timezone=Asia/Shanghai " --conf s 
37112: park.driver.cores=1 --driver-memory 1G --driver-class-path /soft/dataspherestudio/spark-2.3.4-bin-hadoop2.7/conf:/appcom/config/hadoop-config:/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-engi 
37112: nemanager/conf:/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/lib/* --driver-cores 1 --executor-memory 3G --executor-cores 2 --num-executors 1 --queue default --class com.webank.w 
37112: edatasphere.linkis.engine.DataWorkCloudEngineApplication  /soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/lib/linkis-ujes-spark-engine-0.11.0.jar --dwc-conf _req_entrance_instance= 
37112: sparkEntrance,172.17.0.90:9106 --dwc-conf wds.linkis.yarnqueue.memory.max=8G --dwc-conf wds.linkis.preheating.time=9:00 --dwc-conf wds.linkis.instance=1 --dwc-conf wds.linkis.tmpfile.clean.time=10:00 --dwc-con 
37112: f ticketId=02381aac-13ea-40bc-962c-3bacc7b17b71 --dwc-conf dwc.application.instance=172.17.0.90:9105 --dwc-conf spark.driver.memory=1 --dwc-conf spark.executor.instances=1 --dwc-conf creator=IDE --dwc-conf spa 
37112: rk.driver.cores=1 --dwc-conf wds.linkis.yarnqueue=default --dwc-conf wds.linkis.yarnqueue.cores.max=4 --dwc-conf spark.executor.memory=3 --dwc-conf spark.executor.cores=2 --dwc-conf wds.linkis.client.memory.ma 
37112: x=4G --dwc-conf dwc.application.name=sparkEngineManager --dwc-conf user=root --spring-conf eureka.client.serviceUrl.defaultZone=http://127.0.0.1:20303/eureka/ --spring-conf logging.config=classpath:log4j2-engi 
37112: ne.xml --spring-conf spring.profiles.active=engine --spring-conf server.port=37112 --spring-conf spring.application.name=sparkEngine 
37112: SLF4J: Class path contains multiple SLF4J bindings.
37112: SLF4J: Found binding in [jar:file:/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/lib/log4j-slf4j-impl-2.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
37112: SLF4J: Found binding in [jar:file:/soft/dataspherestudio/spark-2.3.4-bin-hadoop2.7/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
37112: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
37112: SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
37112: Exception in thread "main" java.lang.Exception: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
37112: 	at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:288)
37112: 	at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:248)
37112: 	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:120)
37112: 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:130)
37112: 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
37112: [root@gbd-01 ~]# exit
37112: 登出
37112: [root@gbd-01 ~]# exit
37112: 登出
2021-07-28 14:38:24.688 WARN  [ForkJoinPool-1-worker-5] com.webank.wedatasphere.linkis.enginemanager.process.SparkCommonProcessEngine 51 warn - SparkCommonProcessEngine(port: 37112, creator: IDE, user: root) has stopped with exit code Some(0)
2021-07-28 14:38:24.689 INFO  [ForkJoinPool-1-worker-5] com.webank.wedatasphere.linkis.enginemanager.process.SparkCommonProcessEngine 42 info - SparkCommonProcessEngine(port: 37112, creator: IDE, user: root) change state Starting => Dead.
2021-07-28 14:38:24.931 ERROR [Engine-Manager-Thread-12] com.webank.wedatasphere.linkis.enginemanager.impl.EngineManagerImpl 59 error - init SparkCommonProcessEngine(port: 37112, creator: IDE, user: root) failed, now stop and delete it. com.webank.wedatasphere.linkis.enginemanager.exception.EngineManagerErrorException: errCode: 20019 ,desc: init engine failed! Unknown error, please ask admin for help. ,ip: 172.17.0.90 ,port: 9105 ,serviceKind: sparkEngineManager
	at com.webank.wedatasphere.linkis.enginemanager.process.ProcessEngine$class.init(ProcessEngine.scala:93) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.process.CommonProcessEngine.init(CommonProcessEngine.scala:23) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$1.apply$mcV$sp(AbstractEngineManager.scala:77) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$1.apply(AbstractEngineManager.scala:76) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$1.apply(AbstractEngineManager.scala:76) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.8.jar:?]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.8.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

2021-07-28 14:38:24.932 INFO  [Engine-Manager-Thread-12] com.webank.wedatasphere.linkis.enginemanager.impl.EngineFactoryImpl 42 info - ready to delete SparkCommonProcessEngine(port: 37112, creator: IDE, user: root).
2021-07-28 14:38:24.932 INFO  [Engine-Manager-Thread-12] com.webank.wedatasphere.linkis.enginemanager.process.SparkCommonProcessEngine 42 info - try to kill SparkCommonProcessEngine(port: 37112, creator: IDE, user: root) with RPC kill command.
2021-07-28 14:38:24.932 WARN  [Engine-Manager-Thread-12] com.webank.wedatasphere.linkis.enginemanager.impl.EngineFactoryImpl 84 apply - java.lang.NullPointerException: null
	at com.webank.wedatasphere.linkis.enginemanager.process.ProcessEngine$class.shutdown(ProcessEngine.scala:159) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.process.SparkCommonProcessEngine.shutdown(SparkCommonProcessEngine.scala:53) ~[linkis-ujes-spark-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.impl.EngineFactoryImpl$$anonfun$delete$1.apply$mcV$sp(EngineFactoryImpl.scala:113) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.impl.EngineFactoryImpl$$anonfun$delete$1.apply(EngineFactoryImpl.scala:113) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.impl.EngineFactoryImpl$$anonfun$delete$1.apply(EngineFactoryImpl.scala:113) ~[linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:74) [linkis-common-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.impl.EngineFactoryImpl.delete(EngineFactoryImpl.scala:113) [linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10$$anonfun$apply$1.apply$mcV$sp(AbstractEngineManager.scala:84) [linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10$$anonfun$apply$1.apply(AbstractEngineManager.scala:84) [linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10$$anonfun$apply$1.apply(AbstractEngineManager.scala:84) [linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102) [linkis-common-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10.apply(AbstractEngineManager.scala:84) [linkis-ujes-enginemanager-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10.apply(AbstractEngineManager.scala:80) [linkis-ujes-enginemanager-0.11.0.jar:?]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.8.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

2021-07-28 14:38:24.943 INFO  [Engine-Manager-Thread-12] com.webank.wedatasphere.linkis.enginemanager.impl.EngineFactoryImpl 42 info - deleted SparkCommonProcessEngine(port: 37112, creator: IDE, user: root).
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.webank.wedatasphere.linkis.enginemanager.EngineManagerReceiver.com$webank$wedatasphere$linkis$enginemanager$EngineManagerReceiver$$getMsg(EngineManagerReceiver.scala:62)
	at com.webank.wedatasphere.linkis.enginemanager.EngineManagerReceiver.onEngineInitFailed(EngineManagerReceiver.scala:166)
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10$$anonfun$apply$4.apply(AbstractEngineManager.scala:85)
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10$$anonfun$apply$4.apply(AbstractEngineManager.scala:85)
	at scala.Option.foreach(Option.scala:257)
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10.apply(AbstractEngineManager.scala:85)
	at com.webank.wedatasphere.linkis.enginemanager.AbstractEngineManager$$anonfun$requestEngine$10.apply(AbstractEngineManager.scala:80)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**linkis-ujes-spark-entrance Log**
```
2021-07-28 14:32:58.078 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration
2021-07-28 14:37:58.079 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration
2021-07-28 14:38:22.541 INFO  [WebSocket-Server-Event-ListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.server.DefaultEntranceServer 42 info - received a request: {runType=sql, executionCode=show databases;, source={scriptPath=sql}, executeApplicationName=spark, umUser=root, params={variable={}, configuration={special={}, runtime={}, startup={}}}}
2021-07-28 14:38:22.554 INFO  [WebSocket-Server-Event-ListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.interceptor.impl.CSEntranceInterceptor 33 apply - Start to execute CSEntranceInterceptor
2021-07-28 14:38:22.554 INFO  [WebSocket-Server-Event-ListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.interceptor.impl.CSEntranceInterceptor 37 apply - Finished to execute CSEntranceInterceptor
2021-07-28 14:38:22.595 INFO  [WebSocket-Server-Event-ListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.server.DefaultEntranceServer 111 execute - Job IDE_root_6 submitted and taskID is 131
2021-07-28 14:38:22.596 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 42 info - IDE_root_6 change state Inited => Scheduled.
2021-07-28 14:38:22.620 INFO  [sparkEntrance-EventListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.EntranceWebSocketService 209 apply -  retMessage: execID is 030516IDEspark172.17.0.90:9106IDE_root_6, status is Scheduled, websocketTag is c17b1e57-e263-486e-bcbb-2ea6fdc78a64
2021-07-28 14:38:24.934 WARN  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.execute.impl.EngineRequesterImpl 51 warn - request a new engine for (creator: IDE, user: root) failed! reason: null
2021-07-28 14:38:24.935 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.execute.impl.EngineRequesterImpl 42 info - request a new engine for root which requested by IDE, wait for it initial.
2021-07-28 14:38:24.935 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.execute.impl.EngineRequesterImpl 42 info - the engine for user root which requested by IDE has inited.
2021-07-28 14:38:24.936 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 42 info - job IDE_root_6 is onFailure on state Scheduled with errorMsg: Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!.
2021-07-28 14:38:24.949 WARN  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 51 warn - This executor of job(IDE_root_6) in starting status,When kill job need to interrupter consumer Future
2021-07-28 14:38:24.950 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.scheduler.future.BDPFutureTask 42 info - Start to interrupt BDPFutureTask
2021-07-28 14:38:24.950 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.scheduler.future.BDPFutureTask 42 info - Finished to interrupt BDPFutureTask of IDE_rootConsumerThread
2021-07-28 14:38:24.950 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 42 info - IDE_root_6 change state Scheduled => Failed.
2021-07-28 14:38:24.977 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 238 close - job:IDE_root_6 is closing
2021-07-28 14:38:24.977 INFO  [sparkEntrance-EventListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.EntranceWebSocketService 209 apply -  retMessage: execID is 030516IDEspark172.17.0.90:9106IDE_root_6, status is Failed, websocketTag is c17b1e57-e263-486e-bcbb-2ea6fdc78a64
2021-07-28 14:38:24.978 INFO  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 47 info - IDE_root_6 execute failed. Reason: Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!. java.lang.NullPointerException: null

2021-07-28 14:38:24.978 WARN  [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer 55 warn - Ask executor for Job IDE_root_6 failed! java.lang.NullPointerException: null

2021-07-28 14:38:24.978 ERROR [IDE_rootConsumerThread] com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer 112 apply - java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_292]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$2.apply$mcV$sp(FIFOUserConsumer.scala:75) ~[linkis-scheduler-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$2.apply(FIFOUserConsumer.scala:75) ~[linkis-scheduler-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$2.apply(FIFOUserConsumer.scala:75) ~[linkis-scheduler-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102) [linkis-common-0.11.0.jar:?]
	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.run(FIFOUserConsumer.scala:75) [linkis-scheduler-0.11.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Desktop (please complete the following information):**
 - OS:  CentOS 7.3
 - Browser : chrome
 - Version : DSS 0.9.1  Linkis 0.11.0

**Additional context**
When I use the spark-sql command to operate spark, I can execute it correctly and get the results. Is there a problem with my configuration? My profile is as follows：
**linkis-ujes-spark-entrance**
```
wds.linkis.server.restful.scan.packages=com.webank.wedatasphere.linkis.entrance.restful
wds.linkis.engine.application.name=sparkEngine
wds.linkis.enginemanager.application.name=sparkEngineManager
wds.linkis.query.application.name=cloud-publicservice
wds.linkis.console.configuration.application.name=cloud-publicservice
wds.linkis.engine.creation.wait.time.max=20m
wds.linkis.console.variable.application.name=cloud-publicservice
wds.linkis.server.version=v1
hadoop.config.dir=/soft/dataspherestudio/hadoop-2.7.2/etc/hadoop
#spark.config.dir=/appcom/config/spark-config
spark.config.dir=/soft/dataspherestudio/spark-2.3.4-bin-hadoop2.7/conf
wds.linkis.entrance.config.logPath=file:///tmp/linkis/
wds.linkis.server.socket.mode=true
wds.linkis.resultSet.store.path=hdfs:///tmp/linkis
wds.linkis.gateway.url=http://127.0.0.1:9001
```

**linkis-ujes-spark-enginemanager**
linkis.properties
```
wds.linkis.server.restful.scan.packages=com.webank.wedatasphere.linkis.entrance.restful
wds.linkis.engine.application.name=sparkEngine
wds.linkis.server.component.exclude.packages=com.webank.wedatasphere.linkis.engine.,com.webank.wedatasphere.linkis.udf.
wds.linkis.server.version=v1
wds.linkis.console.config.application.name=cloud-publicservice
wds.linkis.engine.udf.app.name=cloud-publicservice
wds.linkis.enginemanager.sudo.script=/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/bin/rootScript.sh
wds.linkis.spark.driver.conf.mainjar=/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/conf:/soft/dataspherestudio/dss/dss_linkis/linkis/linkis-ujes-spark-enginemanager/lib/*
#spark.config.dir=/appcom/config/spark-config
spark.config.dir=/soft/dataspherestudio/spark-2.3.4-bin-hadoop2.7/conf
```
linkis-engine.properties
```
wds.linkis.server.restful.scan.packages=com.webank.wedatasphere.linkis.engine.restful
wds.linkis.engine.application.name=sparkEngine
wds.linkis.server.component.exclude.packages=com.webank.wedatasphere.linkis.enginemanager.,com.webank.wedatasphere.linkis.udf.
wds.linkis.server.component.exclude.classes=com.webank.wedatasphere.linkis.resourcemanager.service.annotation.RMAnnotationParser
wds.linkis.enginemanager.sudo.script=/appcom/tmp/johnnwang/Install/linkis-ujes-spark-enginemanager/bin/rootScript.sh
wds.linkis.server.version=v1
wds.linkis.console.config.application.name=cloud-publicservice
wds.linkis.engine.udf.app.name=cloud-publicservice
hadoop.config.dir=/soft/dataspherestudio/hadoop-2.7.2/etc/hadoop
spark.config.dir=/soft/dataspherestudio/spark-2.3.4-bin-hadoop2.7/conf
wds.linkis.gateway.url=http://127.0.0.1:9001
```

**Comment by coralzu** [comment]
```
: Exception in thread "main" java.lang.Exception: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
37112: 	at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:288)
37112: 	at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:248)
37112: 	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:120)
37112: 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:130)
37112: 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

The reason for the error is that spark-env.sh is not configured with Hadoop_ CONF_ Dir causes。
